'use client';

import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { BarChart3, Clock, FileQuestion, MoreHorizontal, Pencil, Play, Plus, RotateCcw, Sparkles, Trash2 } from 'lucide-react';
import { openContextMenu } from '@/components/ui/ContextMenu';
import { gradeExam, useExams, type Exam } from '@/store/exams';
import { confirmDialog } from '@/store/dialogs';
import { toast } from '@/store/toast';
import { logStudyActivity } from '@/lib/tauri-commands';
import { cn, formatRelativeTime } from '@/lib/utils';
import ExamEditor from './ExamEditor';
import ExamGenerator from './ExamGenerator';
import TakeExam from './TakeExam';
import ExamResults from './ExamResults';

type Screen = { kind: 'list' } | { kind: 'take'; id: string } | { kind: 'results'; id: string };

export default function ExamsTab() {
  const exams = useExams((state) => state.exams);
  const hydrated = useExams((state) => state.hydrated);
  const addExam = useExams((state) => state.addExam);
  const updateExam = useExams((state) => state.updateExam);
  const deleteExam = useExams((state) => state.deleteExam);
  const [screen, setScreen] = useState<Screen>({ kind: 'list' });
  const [editor, setEditor] = useState<{ open: boolean; exam: Exam | null }>({ open: false, exam: null });
  const [generatorOpen, setGeneratorOpen] = useState(false);

  useEffect(() => {
    void useExams.getState().hydrate();
  }, []);

  const stats = useMemo(() => {
    const completed = exams.filter((e) => e.status === 'completed' && typeof e.percentage === 'number');
    const average = completed.length ? Math.round(completed.reduce((sum, e) => sum + (e.percentage ?? 0), 0) / completed.length) : null;
    return { total: exams.length, completed: completed.length, average };
  }, [exams]);

  const start = (exam: Exam) => {
    if (exam.questions.length === 0) {
      toast.warning('This exam has no questions yet');
      return;
    }
    updateExam(exam.id, {
      status: 'in-progress',
      startedAt: new Date().toISOString(),
      deadline: exam.timeLimit > 0 ? Date.now() + exam.timeLimit * 60_000 : undefined,
      questions: exam.questions.map(({ userAnswer, verdict, feedback, ...rest }) => rest),
      score: undefined,
      percentage: undefined,
      completedAt: undefined,
    });
    setScreen({ kind: 'take', id: exam.id });
  };

  const submit = useCallback(
    (id: string) => {
      const exam = useExams.getState().exams.find((e) => e.id === id);
      if (!exam || exam.status === 'completed') {
        setScreen({ kind: 'results', id });
        return;
      }
      const graded = gradeExam(exam.questions);
      const completedAt = new Date().toISOString();
      updateExam(id, {
        ...graded,
        status: 'completed',
        completedAt,
        deadline: undefined,
        attempts: [...(exam.attempts ?? []), { completedAt, ...graded }].slice(-20),
      });
      const seconds = exam.startedAt ? (Date.now() - Date.parse(exam.startedAt)) / 1000 : 0;
      void logStudyActivity('exam', exam.title, seconds, `${graded.percentage}%`).catch(() => undefined);
      setScreen({ kind: 'results', id });
    },
    [updateExam],
  );

  const remove = async (exam: Exam) => {
    const ok = await confirmDialog({ title: `Delete “${exam.title}”?`, message: 'The exam and its results will be removed.', confirmLabel: 'Delete', danger: true });
    if (ok) deleteExam(exam.id);
  };

  const current = screen.kind === 'list' ? undefined : exams.find((e) => e.id === screen.id);

  useEffect(() => {
    if (screen.kind !== 'list' && hydrated && !current) setScreen({ kind: 'list' });
  }, [screen.kind, hydrated, current]);

  if (screen.kind !== 'list' && current) {
    const exam = current;
    if (screen.kind === 'take') {
      return <TakeExam key={exam.id} exam={exam} onExit={() => setScreen({ kind: 'list' })} onSubmit={() => submit(exam.id)} />;
    }
    return <ExamResults exam={exam} onBack={() => setScreen({ kind: 'list' })} onRetake={() => start(exam)} />;
  }

  const empty = hydrated && exams.length === 0;

  return (
    <div className={cn('page', empty && 'page-center')}>
      <header className="page-header">
        <div>
          <h1>Exams</h1>
          <p>
            {stats.total === 0
              ? 'Practice with timed exams written by you or generated by AI'
              : `${stats.total} exam${stats.total === 1 ? '' : 's'} · ${stats.completed} completed${stats.average !== null ? ` · ${stats.average}% average` : ''}`}
          </p>
        </div>
        <div className="page-actions">
          <button type="button" className="btn btn-secondary" onClick={() => setEditor({ open: true, exam: null })}>
            <Plus size={15} /> Write an exam
          </button>
          <button type="button" className="btn btn-primary" onClick={() => setGeneratorOpen(true)}>
            <Sparkles size={15} /> Generate with AI
          </button>
        </div>
      </header>

      {empty ? (
        <div className="empty-state">
          <FileQuestion size={40} strokeWidth={1.4} />
          <h2>No exams yet</h2>
          <p>Generate a practice exam from a topic or one of your documents, or write your own questions.</p>
          <div className="empty-actions">
            <button type="button" className="btn btn-primary" onClick={() => setGeneratorOpen(true)}>
              <Sparkles size={15} /> Generate an exam
            </button>
          </div>
        </div>
      ) : (
        <div className="exam-grid">
          {exams.map((exam) => {
            const mcq = exam.questions.filter((q) => q.type === 'multiple-choice').length;
            const written = exam.questions.length - mcq;
            return (
              <div key={exam.id} className="exam-card" onContextMenu={(event) => openContextMenu(event, [
                { label: 'Edit…', icon: <Pencil size={13} />, onSelect: () => setEditor({ open: true, exam }) },
                { label: 'Delete…', icon: <Trash2 size={13} />, danger: true, onSelect: () => void remove(exam) },
              ])}>
                <div className="exam-card-head">
                  <span className={cn('badge', exam.status === 'completed' ? 'tone-green' : exam.status === 'in-progress' ? 'tone-amber' : 'tone-slate')}>
                    {exam.status === 'completed' ? `${exam.percentage ?? 0}%` : exam.status === 'in-progress' ? 'In progress' : 'Not started'}
                  </span>
                  <button
                    type="button"
                    className="icon-btn icon-btn-sm"
                    onClick={(event) =>
                      openContextMenu(event, [
                        { label: 'Edit…', icon: <Pencil size={13} />, onSelect: () => setEditor({ open: true, exam }) },
                        { label: 'Delete…', icon: <Trash2 size={13} />, danger: true, onSelect: () => void remove(exam) },
                      ])
                    }
                    title="More"
                  >
                    <MoreHorizontal size={15} />
                  </button>
                </div>
                <h3 dir="auto">{exam.title}</h3>
                {exam.subject && <div className="exam-card-subject" dir="auto">{exam.subject}</div>}
                <div className="exam-card-meta">
                  <span>
                    {mcq} choice{written ? ` · ${written} written` : ''}
                  </span>
                  {exam.timeLimit > 0 && (
                    <span>
                      <Clock size={12} /> {exam.timeLimit} min
                    </span>
                  )}
                  <span>{formatRelativeTime(exam.completedAt ?? exam.createdAt)}</span>
                </div>
                <div className="exam-card-actions">
                  {exam.status === 'in-progress' ? (
                    <button type="button" className="btn btn-primary btn-sm" onClick={() => setScreen({ kind: 'take', id: exam.id })}>
                      <Play size={13} /> Resume
                    </button>
                  ) : exam.status === 'completed' ? (
                    <>
                      <button type="button" className="btn btn-secondary btn-sm" onClick={() => setScreen({ kind: 'results', id: exam.id })}>
                        <BarChart3 size={13} /> Results
                      </button>
                      <button type="button" className="btn btn-ghost btn-sm" onClick={() => start(exam)}>
                        <RotateCcw size={13} /> Retake
                      </button>
                    </>
                  ) : (
                    <button type="button" className="btn btn-primary btn-sm" onClick={() => start(exam)}>
                      <Play size={13} /> Start
                    </button>
                  )}
                </div>
              </div>
            );
          })}
        </div>
      )}

      <ExamEditor
        open={editor.open}
        exam={editor.exam}
        onClose={() => setEditor({ open: false, exam: null })}
        onSave={(exam) => {
          if (editor.exam) updateExam(exam.id, exam);
          else addExam(exam);
          setEditor({ open: false, exam: null });
        }}
      />
      <ExamGenerator
        open={generatorOpen}
        onClose={() => setGeneratorOpen(false)}
        onCreated={(exam) => {
          addExam(exam);
          setGeneratorOpen(false);
          toast.success('Exam ready', `${exam.questions.length} questions — press Start when you are ready.`);
        }}
      />
    </div>
  );
}
